### PR TITLE
Add rapp_object_detection node and service

### PR DESCRIPTION
**Pull request by maciek-slon**
New object_detection package added. Related: #87

### CODE REVIEW

**Comment by etsardou** [comment]
Will this package be continued? If yes, you should correct the above issues and provide a way for the node to train based on a set of images.

**Comment by maciek-slon** [comment]
Yes, it is still in development. The question is, however, whether can we rely on existence of ~/rapp_platform_files directory for storing user-trained object models or should it be passed at the platform-deployment stage as a ROS param or something similar?

**Comment by etsardou** [comment]
The ```~/rapp_platform_files``` is created upon the RAPP Platform setup and several configuration files are stored there, thus I would say that its safe to use it.

**Comment by maciek-slon** [comment]
See new pull request: #346

**Pull request closed without merging**
