### PR TITLE
Wut path planner

### PR DESCRIPTION
**Pull request by etsardou**
I took the liberty of creating a new pull request to ```devel```, as this is our pre-release branch. ```master``` is only for releases.

### CODE REVIEW

**Comment by etsardou** [comment]
Some comments:

First of all you have to rebase ```wut_path_planner``` branch to the ```devel``` branch, in order to get all latest changes.

Concerning the code functionality I can see you added two new ros packages: ```rapp_map_server``` and ```rapp_path_planning```. If I understand correct, in the ```rapp_map_server``` package you have emulated the functionality of ROS's map_server, i.e. you load an image (containing the map) and you manually read the corresponding yaml file. Then the ```rapp_map_server``` publishes the map in a ROS topic. Then ```rapp_path_planning``` gets the map from this topic and produces a path with the ```plan_path``` service.

Your approach is quite fine but has some problems regarding its integration in a cloud environment:
- One problem is that the maps are predefined, thus a new user cannot give a new map (or an old user cannot change their own). For that reason I would suggest to remove the maps from there and create a HOP service (with @klpanagi) called ```set_map``` which will contain an image and the necessary variables to put in the yaml file. This service will get the username as well, thus it can store the map and create the yaml in the user's folder in ```~/rapp_platform_files/maps``` folder. For example the user ```rapp``` will have his own map stored in ```~/rapp_platform_files/maps/rapp/```.
- The ```rapp_path_planning``` node should have another HOP service (again @klpanagi will help you) that gets the two points for path planning and a username. This HOP service should call the ```plan_path``` ROS service you already have. The difference in this approach is that the ```rapp_path_planner``` should call a ROS service that exists in ```rapp_map_server``` (and not subscribe to a topic) which must take the username, search for the user's map, load it and return it via this service for the path planning to occur. This way the interfaces are much "clearer" since everything is done via direct services invocation and not with message topics (that anyone can subscribe to, thus another node may mistakenly take this map)

After you have refactored the code following the above notions, you have to check some minor issues:
-  Add a page (or pages) in the [wiki](https://github.com/rapp-project/rapp-platform/wiki) describing the functionality of your nodes. Essentially you should copy-paste the README contents.
- Add some integration tests with the help of @klpanagi. He will be responsible of creating the python API for the HOP services as well.
- Add Doxygen-style comments to your code, above each class and function, in order to automatically produce the [documentation](http://rapp-project.github.io/rapp-platform/documentation.html)

Thank you!

**Comment by etsardou** [comment]
NOTE: Your tests have passed, the Travis CI failed for another reason.

**Comment by etsardou** [comment]
@dudekw Please do not use merge. Reset your branch to c2e6a9ecbf941c1cd4e6f901d2786e77979c01be and **rebase** to devel. if you want help I can do it and you can continue from there.

**Comment by dudekw** [comment]
I hope that this barnch network looks fine now.

**Comment by etsardou** [comment]
Yes, now it is great, ty!

**Pull request closed without merging**
