### PR TITLE
Path planning fix

### LINKED ISSUE #322: Path planning fails on catkin_make
https://travis-ci.org/rapp-project/rapp-platform/jobs/134957593#L963 
The issue was also recreated on a clean machine.

@dudekw @maciek-slon Please have this issue resolved until 10/6, since we are preparing for the new release. If the node is not ready until then, we will remove it from the master branch and have it re-applied in a later release/patch.

### PR DESCRIPTION
**Pull request by dudekw**
resolves #322, limits poses in response path. Merge into one commit

### CODE REVIEW

**Comment by etsardou** [comment]
Hi @dudekw, unfortunately the issue does not seem to be resolved:
- https://travis-ci.org/rapp-project/rapp-platform/jobs/135234619#L980
- https://travis-ci.org/rapp-project/rapp-platform/jobs/135234620#L975
- https://travis-ci.org/rapp-project/rapp-platform/jobs/135234621#L974

**Comment by dudekw** [comment]
The problem is, path_planning_fix branch checks are successful ( https://travis-ci.org/rapp-project/rapp-platform/builds/135227036 ), but pull request is not. Is it possible that Travis checks every commit from the beginning separately?

**Comment by etsardou** [comment]
Ah ok, we will check it locally and let you know!

**Comment by athallas** [comment]
Hi @dudekw, the issue seems to be resolved. Additionally, I checked everything locally and everything seems fine apart from a warning produced at `catkin_make`. Specifically:

```
CMake Warning at rapp-platform/rapp_path_planning/rapp_map_server/CMakeLists.txt:37 (add_executable):
  Cannot generate a safe runtime search path for target rapp_map_server
  because there is a cycle in the constraint graph:

    dir 0 is [/opt/ros/indigo/lib]
      dir 1 must precede it due to runtime library [libimage_loader.so]
    dir 1 is [/home/aris/rapp_platform/rapp-platform-catkin-ws/devel/lib]
      dir 0 must precede it due to runtime library [libimage_loader.so]

  Some of these libraries may not be found correctly.
```

Any insights regarding this?

**Comment by dudekw** [comment]
Build and rostest on my local VM are successful:
```
rostest rapp_path_planning functional_tests.launch 
... logging to /home/rapp/.ros/log/rostest-rapp-pl-VirtualBox-29024.log
[ROSUNIT] Outputting test results to /home/rapp/.ros/test_results/rapp_path_planning/rostest-test_path_planning_functional_tests.xml
[ERROR] [1465063358.559649572]: Failed to get a plan.
[ERROR] [1465063358.647253918]: Input algorithm does not exist
[ERROR] [1465063358.761894297]: Input map does not exist
[ERROR] [1465063358.870362473]: Input robot_type does not exist
testpath_planning_functional ... ok

[ROSTEST]-----------------------------------------------------------------------

[rapp_path_planning.rosunit-path_planning_functional/test_getPath][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_map_upload][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_map_upload_error][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_planFound][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_planNotFound][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_wrongAlgorithm][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_wrongMap][passed]
[rapp_path_planning.rosunit-path_planning_functional/test_wrongRobot][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 0`
```

Now, ROS package - `map_server` is not required any more, so maintainer of `rapp-platform-scripts` repository can cut [this line](https://github.com/rapp-project/rapp-platform-scripts/blob/devel/setup/2_ros_setup.sh#L59) off.

**Comment by dudekw** [comment]
@athallas @etsardou  Please let me know if any changes are needed.

**Comment by athallas** [comment]
@dudekw Yes, i've tested them locally and i'm waiting for the travis build to finish, since i had to restart two of the build jobs. Once they are done i will merge the branch into devel unless other issues emerge. I will also update the scripts, as you suggested.

**Pull request closed without merging**
